config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :users
  resources :posts, except: [:edit, :update] do
    resources :likes, only: [:create, :destroy, :index]
    resources :comments, only: [:create, :destroy, :index]
  end
  resources :friend_requests, only: [:create, :destroy]
  resources :friendships, only: [:index, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
  validates :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :correct_user, only: :destroy

    def new
        @post = Post.new
    end

    def create
        @post = current_user.posts.build(posts_params)
        if @post.save
            flash[:success] = 'Post created!'
            redirect_to @post
        else
            render 'new'
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def index
        friend_ids = "SELECT friend_id FROM friendships WHERE user_id = :user_id"
        @posts = Post.where("user_id IN (#{friend_ids}) OR user_id = :user_id", user_id: current_user.id )
    end

    def destroy
        @post.destroy
        flash[:success] = 'Post deleted'
        redirect_to request.referrer || root_url
    end

    private

    def posts_params
        params.require(:post).permit(:body)
    end

    def correct_user
        @post = current_user.posts.find_by(id: params[:id])
        redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like.html.erb
<%= form_with model: [post, post.likes.build], remote: true do |f| %>
    <%= f.submit "Like" %>
<% end %>

app/views/posts/_like_form.html.erb
<%= content_tag(:div, nil, id: "like-form-#{post.id}") do
        if current_user.likes?(post)
            render partial: 'posts/unlike', locals: { post: post }
        else
            render partial: 'posts/like', locals: { post: post }
        end
end %>

app/views/posts/_post.html.erb
<article>
    <p><%= link_to post.user.name, post.user %></p>
    <p><%= post.body %></p>
    <%= render partial: 'posts/like_form', locals: { post: post } %>
    <span id="post-<%=post.id%>-likes">
        <%= post.likes.count %>
    </span> 
    <%= link_to "likes", post_likes_path(post) %>
    <p>Posted at <%= post.created_at %></p>
    <ul>
        <%= render post.comments %>
    </ul>
    <%= render partial: 'comments/comment_form', locals: { post: post } %>
    <p><%= link_to 'permalink', post %>
</article>

app/views/posts/_unlike.html.erb
<%= form_with model: [post, post.likes.find_by(user: current_user)],
                method: :delete, remote: true do |f| %>
    <%= f.submit "Unlike" %>
<% end %>

app/views/posts/index.html.erb
<h1>Timeline</h1>

<%= render @posts %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= form_with model: @post do |f| %>
    <%= f.text_area :body %>
    <%= f.submit "Post" %>
<% end %>

app/views/posts/show.html.erb
<%= render @post %>